apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-pugi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-pugi
    app.kubernetes.io/part-of: ci10t-776-0089-app
  name: devfile-sample-pugi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-pugi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-pugi
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0089-tenant/ci10t-776-0089-app/devfile-sample-pugi@sha256:2e663294c40899063558fb67e97db8c1e43e26e7078571ccb0c5cab912152008
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
